import json,pathlib,html,collections
P=pathlib.Path(__file__).resolve().parents[1]
read=lambda p:json.loads((P/p).read_text())
e=lambda t:html.escape(str(t))
d=read('report/content.json');downloads=read('inventory/downloads.json')
ok=[a for a in downloads if a['status']=='downloaded']; unique={a['sha256']:a['bytes'] for a in ok}
css='''*{box-sizing:border-box}body{margin:0;background:#f7f7f8;color:#17191d;font:17px/1.65 -apple-system,BlinkMacSystemFont,sans-serif}main{max-width:1120px;margin:auto;padding:56px 28px}h1{font:60px/1.07 -apple-system,BlinkMacSystemFont,sans-serif;max-width:850px}h2{font:34px/1.2 -apple-system,BlinkMacSystemFont,sans-serif;margin:0 0 25px}h3{font-size:20px}section{padding:45px 0;border-top:1px solid #d8d9df;scroll-margin-top:30px}p{max-width:950px}a{color:#394d72}nav{display:flex;flex-wrap:wrap;gap:10px;margin:24px 0}nav a,.pill{padding:8px 15px;background:#e9ebf0;border-radius:25px;text-decoration:none;font-size:14px}table{width:100%;border-collapse:collapse;font-size:14px;background:#fff9}td,th{text-align:left;padding:14px;vertical-align:top;border-bottom:1px solid #dedfe4}th{background:#17191d;color:white}.table{overflow:auto;margin:25px 0}td{min-width:170px}.sources{font-size:13px;overflow-wrap:anywhere}.sources a{display:block}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;padding:24px 0}.stats b{font:38px -apple-system,BlinkMacSystemFont,sans-serif;display:block}.stats span{font-size:13px}.gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.gallery img{width:100%;height:260px;object-fit:contain;background:#eceef2;border-radius:12px}figcaption{font-size:13px}figure{margin:0}input{font:inherit;width:100%;padding:16px;border:1px solid #cbd0d8;border-radius:12px;background:#fff}small{color:#707580}details{padding:15px 0}code{font-size:13px}@media(max-width:650px){h1{font-size:40px}main{padding:25px 20px}.stats{grid-template-columns:repeat(2,1fr)}.gallery{grid-template-columns:1fr}h2{font-size:28px}}'''
def link(u,label=None):return '<a href="'+e(u)+'">'+e(label or u)+'</a>'
def table(headers,rows):
 return '<div class="table"><table><thead><tr>'+''.join('<th>'+e(v)+'</th>' for v in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+(link(v) if str(v).startswith(('http','../')) else e(v))+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def page(title,body):return '<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+e(title)+'</title><style>'+css+'</style><main>'+body+'</main></html>'
body='<small>SALINI · ИССЛЕДОВАНИЕ · 6 ОКТЯБРЯ 2026</small><h1>Из сайта — в личное пространство Salini.</h1><p>'+e(d['scope'])+'</p><div class="stats">'+''.join('<div><b>'+n+'</b><span>'+t+'</span></div>' for n,t in [('608','проверенных URL'),('326','страниц карточек'),(str(len(ok)),'скачанных ресурсов'),('50','требований в матрице')])+'</div>'
body+='<nav>'+link('requirements.html','Матрица требований')+link('library.html','Библиотека материалов')+link('../inventory/summary.json','Данные исследования')+'</nav><details><summary>Содержание отчёта</summary><nav>'+''.join(link('#'+s['id'],s['title']) for s in d['sections'])+'</nav></details>'
for s in d['sections']:
 body+='<section id="'+s['id']+'"><h2>'+e(s['title'])+'</h2>'+''.join('<p>'+e(p)+'</p>' for p in s.get('paragraphs',[]))
 if 'table' in s:body+=table(s['table']['headers'],s['table']['rows'])
 if s['id']=='reference':body+='<div class="gallery">'+''.join('<figure>'+link('../evidence/'+f,'Открыть кадр')+'<img loading="lazy" src="../evidence/'+f+'"><figcaption>'+cap+'</figcaption></figure>' for f,cap in [('business-reference-seek-mid.jpg','Выбран транспорт · около 28 с'),('business-reference-seek-late.jpg','Выбрана зона склада · около 48 с'),('business-reference-seek-end.jpg','Другая площадка · около 66 с')])+'</div>'
 if s['id']=='ux':body+='<div class="gallery">'+''.join('<figure><img loading="lazy" src="../evidence/'+f+'"><figcaption>'+cap+'</figcaption></figure>' for f,cap in [('aria-mobile-top.jpg','Начало карточки Aria'),('aria-configured-mobile.jpg','Проверенная конфигурация'),('checkout-mobile.jpg','Форма заявки')])+'</div>'
 body+='<div class="sources">Источники'+''.join(link(u) for u in s.get('sources',[]))+'</div></section>'
body+='<section><h2>19. Собранный архив</h2><p>Сохранены '+str(len(ok))+' ресурсов, '+str(len(unique))+' уникальных по содержимому, '+str(round(sum(unique.values())/1e9,2))+' ГБ уникальных данных. Повторяющиеся файлы дедуплицированы. Полный реестр содержит 6 264 URL ресурсов; локальная подборка охватывает прямые документы/модели и репрезентативные изображения. 10 ресурсов вернули HTTP 404. На Яндекс Диске зафиксированы 175 публичных ссылок, их содержимое целиком не скачивалось.</p><p>В каталоге извлечены 326 карточек и 300 непустых уникальных ID, включая аксессуары и опции. Это не число всех SKU. Нормализовано 270 дилерских записей из публичных выборок, не вся заявленная сеть. HTML-архив не является автономной копией работающего магазина.</p><p>Исходное ТЗ, снимки и большой архив остаются локально. В Git включены код сбора, инвентаризация и отчёт. Локальные ссылки на исключённые файлы работают из этой рабочей папки.</p>'+table(['Файл','Назначение'],[['../inventory/pages.json','Статусы и метаданные каждого URL'],['../inventory/products.json','Карточки, варианты, характеристики, документы'],['../inventory/dealers.json','Салоны и экспозиции с источниками'],['../inventory/downloads.json','URL, локальный путь, SHA-256 и статус скачивания'],['../inventory/assets.json','Полный список найденных ресурсов'],['../inventory/external-resources.json','Внешние ссылки на модели/материалы'],['../inventory/workbook-structure.json','Листы и формулы найденных XLSX'],['../inventory/ux-findings.json','16 наблюдений и решений']])+'</section>'
(P/'report/index.html').write_text(page(d['title'],body))
req=read('inventory/requirements-matrix.json')
(P/'report/requirements.html').write_text(page('Salini — матрица требований',link('index.html','← К исследованию')+'<h1>50 требований.<br>Одна система.</h1><p>Основа — пункты предоставленного ТЗ. Два требования режима руководителя добавлены из запроса пользователя. Этапы являются предложением для приложения.</p>'+table(['ID / пункт ТЗ','Требование','Что проверено','Адаптация','Зависимость / этап'],[[r['id']+' · '+r['brief'],r['area']+': '+r['requirement'],r['current_evidence'],r['app_adaptation'],r['dependency']+' / '+r['phase']] for r in req])))
rows=[[a.get('label') or a['local'].split('/')[-1],a['extension'],round(a['bytes']/1024), '../'+a['local'],a['url']] for a in ok]
(P/'report/library.html').write_text(page('Salini — библиотека',link('index.html','← К исследованию')+'<h1>Материалы Salini.</h1><p>Поиск по имени или формату. Файлы собраны для исследования и прототипа; источники и контрольные суммы сохранены в инвентаризации. Права на брендовые материалы принадлежат их владельцам.</p><input id="q" placeholder="ARIA, GRECA, PDF, USDZ…" aria-label="Поиск материалов">'+table(['Файл','Формат','КБ','Локальная копия','Источник'],rows)+'<script>document.querySelector("#q").oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll("tbody tr").forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(q))}</script>'))
print('Report built',len(ok),'files',round(sum(unique.values())/1e9,2),'GB')
