import SwiftUI
import SpriteKit

@main struct SaliniInsightLabApp:App {var body:some Scene{WindowGroup{InsightLabView()}}}
struct InsightLabView:View {
    @StateObject private var d=InsightDriver()
    @Environment(\.scenePhase) private var phase
    private let ink=Color(red:0.09,green:0.14,blue:0.2)
    var body:some View {
        VStack(spacing:0){
            HStack(spacing:11){Image("salini-logo").resizable().scaledToFit().frame(width:79,height:34).accessibilityLabel("Salini");Rectangle().fill(ink.opacity(0.2)).frame(width:1,height:23);Text("Insight").font(.system(size:22,weight:.light)).tracking(-0.8);Spacer();Button{d.infoOpen=true}label:{Image(systemName:"info.circle").font(.system(size:18,weight:.light))}.accessibilityLabel("О сцене")}.padding(.horizontal,24).padding(.top,7).padding(.bottom,14)
            ZStack(alignment:.topLeading){
                SpriteView(scene:d.scene,preferredFramesPerSecond:60,options:[.ignoresSiblingOrder]).accessibilityLabel("Архитектурная сцена. Контроль качества и движущаяся партия")
                HStack{Text("ДЕМО · УЧАСТОК 04").font(.system(size:8,weight:.semibold)).tracking(1.4).foregroundStyle(.secondary);Spacer();HStack(spacing:5){Button{d.zoom=max(1,d.zoom-0.05)}label:{Image(systemName:"minus")}.disabled(d.zoom<=1).accessibilityLabel("Отдалить");Text("\(Int((d.zoom*100).rounded()))%").font(.system(size:8)).monospacedDigit().frame(width:29);Button{d.zoom=min(1.1,d.zoom+0.05)}label:{Image(systemName:"plus")}.disabled(d.zoom>=1.099).accessibilityLabel("Приблизить")}.font(.system(size:12,weight:.light)).padding(8).background(.regularMaterial,in:Capsule())}.padding(.horizontal,22).padding(.top,4)
            }.clipped()
            board.padding(.horizontal,13).padding(.top,-9).padding(.bottom,5)
        }.background(Color(red:0.93,green:0.94,blue:0.95)).foregroundStyle(ink).preferredColorScheme(.light)
        .sheet(item:$d.selected){zone in detail(zone).presentationDetents([.height(340)]).presentationDragIndicator(.visible)}
        .sheet(isPresented:$d.layersOpen){settings.presentationDetents([.height(430)]).presentationDragIndicator(.visible)}
        .sheet(isPresented:$d.infoOpen){information.presentationDetents([.medium,.large]).presentationDragIndicator(.visible)}
        .onChange(of:phase){_,p in d.isActive=p == .active}
    }
    private var board:some View {
        VStack(alignment:.leading,spacing:0){
            HStack{VStack(alignment:.leading,spacing:7){HStack(spacing:6){Circle().fill(Color(red:0.77,green:0.6,blue:0.28)).frame(width:5,height:5);Text(["ГОТОВО К ОТГРУЗКЕ","ПАРТИЯ В ПУТИ","ПЕРЕДАНО НА ОТГРУЗКУ"][d.frame.stage]).font(.system(size:8,weight:.semibold)).tracking(1)}.foregroundStyle(Color(red:0.53,green:0.4,blue:0.18));Text("Партия 024").font(.system(size:23,weight:.medium)).tracking(-0.7);Text(d.frame.title).font(.system(size:10)).foregroundStyle(.secondary).lineLimit(1).minimumScaleFactor(0.8)};Spacer(minLength:6);Button{d.playing.toggle()}label:{Image(systemName:d.playing ? "pause":"play").font(.system(size:13)).frame(width:37,height:37).background(.white.opacity(0.65),in:Circle()).overlay(Circle().stroke(ink.opacity(0.08),lineWidth:1))}.accessibilityLabel(d.playing ? "Приостановить":"Продолжить")}
            HStack(spacing:0){metric("12","На контроле",.quality);Divider().frame(height:37);metric("2","К отгрузке",.packing).padding(.leading,17);Divider().frame(height:37);metric("02","Рейс",.carrier).padding(.leading,17)}.padding(.top,20)
            HStack{Text("Фиксированный ракурс").foregroundStyle(.secondary);Spacer();Button("Слои и движение"){d.layersOpen=true}}.font(.system(size:8)).padding(.top,12).padding(.top,14).overlay(alignment:.top){Rectangle().fill(ink.opacity(0.06)).frame(height:0.5).padding(.top,14)}
        }.padding(.horizontal,21).padding(.top,20).padding(.bottom,12).background(.regularMaterial,in:RoundedRectangle(cornerRadius:27)).overlay(RoundedRectangle(cornerRadius:27).stroke(.white.opacity(0.9),lineWidth:1)).shadow(color:ink.opacity(0.05),radius:20,y:7)
    }
    private func metric(_ number:String,_ title:String,_ zone:LabZone)->some View {Button{d.selected=zone}label:{VStack(alignment:.leading,spacing:6){Text(number).font(.system(size:21,weight:.medium)).tracking(-0.6);Text(title).font(.system(size:9)).foregroundStyle(.secondary)}.frame(maxWidth:.infinity,alignment:.leading)}.buttonStyle(.plain)}
    private func detail(_ zone:LabZone)->some View {VStack(alignment:.leading,spacing:17){Text("SALINI INSIGHT · ДЕМО").font(.system(size:9,weight:.medium)).tracking(1.2).foregroundStyle(.secondary);Text(zone.rawValue).font(.system(size:29)).tracking(-1);Text(zone == .quality ? "12 изделий находятся на участке. Партия 024 прошла контроль и передаётся во внутреннюю логистику.":"Два упакованных изделия движутся одним составом к отгрузке. Камера сохраняет общий вид и не приближается автоматически.").font(.system(size:14)).foregroundStyle(.secondary).lineSpacing(3);Spacer(minLength:0);Button{d.seek(zone == .quality ? 2:16);d.selected=nil;d.playing=true}label:{Text("К действию").frame(maxWidth:.infinity).padding(15).background(ink,in:RoundedRectangle(cornerRadius:14)).foregroundStyle(.white)}.font(.system(size:14,weight:.medium));Text("Все значения и процессы демонстрационные.").font(.system(size:10)).foregroundStyle(.secondary)}.padding(27)}
    private var settings:some View {VStack(alignment:.leading,spacing:18){Text("Сцена и движение").font(.system(size:27)).tracking(-1);Toggle("Транспорт и груз",isOn:$d.showCarrier);Toggle("Свет и колёса",isOn:$d.showActivity);Toggle("Метки участков",isOn:$d.showLabels);Slider(value:Binding(get:{d.time},set:{d.seek($0)}),in:0...39.99).accessibilityLabel("Время цикла");Button("Начать сначала"){d.seek(0);d.playing=true;d.layersOpen=false}.frame(maxWidth:.infinity).padding(14).background(ink.opacity(0.08),in:RoundedRectangle(cornerRadius:13));Text("Ракурс закреплён. Масштаб ограничен 110%. Движение и состояния вычисляются нативно.").font(.system(size:11)).foregroundStyle(.secondary)}.font(.system(size:14)).tint(ink).padding(27)}
    private var information:some View {VStack(alignment:.leading,spacing:18){Text("АРХИТЕКТУРНАЯ ПРОБА · 02").font(.system(size:9,weight:.semibold)).tracking(1.2);Text("Целая сцена.\nУправляемое движение.").font(.system(size:30)).tracking(-1);Text("Окружение и транспорт созданы встроенной генерацией изображений OpenAI. Состав движется по дороге, колёса и сигнал связаны с его состоянием. Камера сохраняет дальний ракурс.");Text("Это художественная проба одного участка. Архитектура, техника, форма изделий и данные не являются обмером или подтверждённой схемой производства Salini. Людей, погрузку и реальное управление оборудованием здесь не моделируем.").foregroundStyle(.secondary);Spacer()}.font(.system(size:14)).lineSpacing(4).padding(27)}
}
